apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  source:
    path: app
    repoURL: https://gitlab.com/adrabenche/dh-exercise.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dh-examen
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
